CREATE TABLE public.user_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    username TEXT,
    session_token TEXT,
    quote_token TEXT,
    quote_token_expiration TIMESTAMPTZ
);
