CREATE TABLE IF NOT EXISTS public.tastytrade_quotes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at     timestamptz NOT NULL DEFAULT now(),
    event_type      text NOT NULL,
    symbol          text NOT NULL,
    bid_price       double precision,
    ask_price       double precision,
    last_price      double precision,
    bid_size        double precision,
    ask_size        double precision,
    raw_payload     jsonb
);

CREATE INDEX IF NOT EXISTS idx_tastytrade_quotes_symbol_time
    ON public.tastytrade_quotes (symbol, received_at DESC);
